environment: prod
replicaCount: 1
image:
  repository: 485701710361.dkr.ecr.eu-north-1.amazonaws.com/my-devops-cicd-demo
  tag: "1.0.0-<SHA>"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
resources: {}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
