name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*-dev'
      - 'v*.*.*-test'
      - 'v*.*.*-prod'

jobs:
  kickoff_codebuild:
    runs-on: ubuntu-latest
    permissions:
      id-token: write         # for OIDC
      contents: read          # to clone the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start AWS CodeBuild
        id: codebuild
        uses: aws-actions/aws-codebuild-run-build@v2
        with:
          project-name: devops-build
          # Pass along the Git tag so CodeBuild can pick it up if you like
          environment-variables: |
            TAG=${{ github.ref_name }}
        # Use the same OIDC role you set up earlier
        env:
          AWS_REGION: eu-north-1
          AWS_ROLE_TO_ASSUME: arn:aws:iam::485701710361:role/github-actions-role

  wait_for_completion:
    needs: kickoff_codebuild
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CodeBuild to finish
        uses: aws-actions/aws-codebuild-run-build@v2
        with:
          project-name: devops-build
          wait-for-completion: true
        env:
          AWS_REGION: eu-north-1
          AWS_ROLE_TO_ASSUME: arn:aws:iam::485701710361:role/github-actions-role
